repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: debug-statements
    -   id: destroyed-symlinks
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]



#
# Fail fast
#

-   repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.15
    hooks:
    - id: validate-pyproject
      fail_fast: true

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    # Syntax
    -   id: check-toml
        fail_fast: true
    -   id: check-json
        fail_fast: true
    -   id: check-yaml
        fail_fast: true

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-ast
        fail_fast: true

#
# Modifiers
#

-   repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.2.0
    hooks:
    -   id: rm-unneeded-f-str

# Last modifier: Coding Standard
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black

#
# Static Checks
#

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    # Python
    -   id: python-use-type-annotations
    -   id: python-no-log-warn
    # Documentation
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.7
    hooks:
    - id: ruff
